'use client';
import { usePathname } from 'next/navigation';
import './globals.css';
import { Footer, Nav } from '@/components';
import { Inter } from 'next/font/google';
import DashboardLayout from './dashboard/layout';
import { Header, Sidebar } from '@/components/dashboard';
import { Provider } from 'react-redux';
import useAuth from './auth/useAuth';
import { LOGIN_ROUTE } from './contstants';
import { useEffect, useState } from 'react';
const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const pathname = usePathname();
  // const isAuthenticated = useAuth();
  if (pathname.startsWith('/dashboard')) {
    return (
      <html lang="en">
        <body>
          <Header />
          <DashboardLayout>
            <Sidebar />
            {children}
          </DashboardLayout>
        </body>
      </html>
    );
  }
  // else if (typeof window !== 'undefined') {
  //   window.location.href = "/login";
  //   return null;
  // }

  return (
    <html lang="en">
      <body>
        <Nav />
        <main className="mt-[-80px]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
