'use client';
import { usePathname } from 'next/navigation';
import './globals.css';
import { Footer, Nav } from '@/components';
import { Inter } from 'next/font/google';
import DashboardLayout from './dashboard/layout';
import { Header, Sidebar } from '@/components/dashboard';
const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  if (pathname.startsWith('/dashboard')) {
    return (
      <html lang="en">
        <body>
          <Header />
          <DashboardLayout>
            <Sidebar />
            {children}
          </DashboardLayout>
        </body>
      </html>
    );
  }
  return (
    <html lang="en">
      <body>
        <Nav />
        <main className="mt-[-80px]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
